apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: backend-tls-certificate
  namespace: default
spec:
  dnsNames:
    - 'backend-staging.vyntix.tech'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-tls-certificate
  namespace: argocd
spec:
  dnsNames:
    - 'argo-staging.vyntix.tech'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-tls-certificate
  namespace: monitoring
spec:
  dnsNames:
    - 'grafana-staging.vyntix.tech'