apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  source:
    helm:
      values: |
        installCRDs: true
        serviceAccount:
          create: false
          name: external-secrets-operator-sa
          annotations:
            iam.gke.io/gcp-service-account: gke-external-secrets-sa@prod-64465.iam.gserviceaccount.com